name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWD }}
    
    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.USER }}/ai-service:${{ github.sha }} ./src/ai-service
        docker build -t ${{ secrets.USER }}/makeline-service:${{ github.sha }} ./src/makeline-service
        docker build -t ${{ secrets.USER }}/order-service:${{ github.sha }} ./src/order-service
        docker build -t ${{ secrets.USER }}/product-service:${{ github.sha }} ./src/product-service
        docker build -t ${{ secrets.USER }}/store-admin:${{ github.sha }} ./src/store-admin
        docker build -t ${{ secrets.USER }}/store-front:${{ github.sha }} ./src/store-front
        docker build -t ${{ secrets.USER }}/virtual-customer:${{ github.sha }} ./src/virtual-customer
        docker build -t ${{ secrets.USER }}/virtual-worker:${{ github.sha }} ./src/virtual-worker
        docker push ${{ secrets.USER }}/ai-service:${{ github.sha }}
        docker push ${{ secrets.USER }}/makeline-service:${{ github.sha }}
        docker push ${{ secrets.USER }}/order-service:${{ github.sha }}
        docker push ${{ secrets.USER }}/product-service:${{ github.sha }}
        docker push ${{ secrets.USER }}/store-admin:${{ github.sha }}
        docker push ${{ secrets.USER }}/store-front:${{ github.sha }}
        docker push ${{ secrets.USER }}/virtual-customer:${{ github.sha }}
        docker push ${{ secrets.USER }}/virtual-worker:${{ github.sha }}
      
    - name: Update Kubernetes manifests
      run: |
        for service in ai-service makeline-service order-service product-service store-admin store-front virtual-customer virtual-worker; do
          sed -i 's|image: .*'${service}'.*|image: ${{ secrets.USER }}/'${service}':${{ github.sha }}|' ./k8s/${service}-deployment.yaml
        done

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update image tags" || exit 0
        git push
            
            
    
